
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  empDATE DATE NOT NULL,
  age INTEGER NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark','2024-10-17', 20);
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', '2024-08-11', 30);
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', '2024-10-18', 50);
INSERT INTO EMPLOYEE VALUES (0004, ' Abgail', '2024-04-10', 40);

-- fetch 
SELECT * FROM EMPLOYEE;
-- SELECT AVG(age) FROM EMPLOYEE;
-- SELECT SUM(age) FROM EMPLOYEE;
-- SELECT COUNT(empId) FROM EMPLOYEE;
-- SELECT MIN(age) FROM EMPLOYEE;
-- SELECT MAX(empId), MIN(empId) FROM EMPLOYEE;
-- SELECT CONCAT(name, ' :)') FROM EMPLOYEE;
-- SELECT CONCAT(name, ' ', age) FROM EMPLOYEE;
-- SELECT CONCAT('Nome: ',name) FROM EMPLOYEE;

-- SELECT UPPER(name) FROM EMPLOYEE;
-- SELECT LOWER(name) FROM EMPLOYEE;

-- SELECT TRIM(name) FROM EMPLOYEE
-- WHERE empId = 004;

-- SELECT TRIM (' Abgail') AS name_correct;

-- SELECT CAST(age AS VARCHAR(1)) FROM EMPLOYEE;

-- SELECT NOW();
-- SELECT empDATE + INTERVAL '3 days' FROM EMPLOYEE;
-- SELECT '2024-10-17'::date + INTERVAL '3 months';

-- SELECT EXTRACT(YEAR FROM empDATE) FROM EMPLOYEE;
-- SELECT EXTRACT(DAY FROM empDATE) FROM EMPLOYEE;
-- SELECT EXTRACT(MONTH FROM empDATE) FROM EMPLOYEE;